/* Generated by Yosys 0.48+45 (git sha1 8acc77c1e, clang++ 18.1.8 -fPIC -O3) */

(* src = "../src/spi_mem.sv:22.1-49.10" *)
module spi_mem(data_out, clk, add, data_in, rwb, rstn);
  (* src = "../src/spi_mem.sv:0.0-0.0" *)
  wire [2047:0] _00_;
  wire _01_;
  wire _02_;
  (* src = "../src/spi_mem.sv:0.0-0.0" *)
  wire [32:0] _03_;
  (* src = "../src/spi_mem.sv:0.0-0.0" *)
  wire [2047:0] _04_;
  (* src = "../src/spi_mem.sv:0.0-0.0" *)
  wire [2047:0] _05_;
  (* src = "../src/spi_mem.sv:0.0-0.0" *)
  wire [2047:0] _06_;
  (* src = "../src/spi_mem.sv:0.0-0.0" *)
  wire [2047:0] _07_;
  (* src = "../src/spi_mem.sv:0.0-0.0" *)
  wire [15:0] _08_;
  (* src = "../src/spi_mem.sv:29.16-29.19" *)
  input [6:0] add;
  wire [6:0] add;
  (* src = "../src/spi_mem.sv:28.10-28.13" *)
  input clk;
  wire clk;
  (* src = "../src/spi_mem.sv:30.17-30.24" *)
  input [15:0] data_in;
  wire [15:0] data_in;
  (* src = "../src/spi_mem.sv:31.22-31.30" *)
  output [15:0] data_out;
  reg [15:0] data_out;
  (* src = "../src/spi_mem.sv:35.24-35.27" *)
  reg [2047:0] mem;
  (* src = "../src/spi_mem.sv:33.10-33.14" *)
  input rstn;
  wire rstn;
  (* src = "../src/spi_mem.sv:32.10-32.13" *)
  input rwb;
  wire rwb;
  assign _00_ = mem & (* src = "../src/spi_mem.sv:0.0-0.0" *) _04_;
  (* src = "../src/spi_mem.sv:37.4-47.7" *)
  always @(posedge clk)
    if (!rstn) data_out <= 16'h0000;
    else if (rwb) data_out <= _08_;
  (* src = "../src/spi_mem.sv:37.4-47.7" *)
  always @(posedge clk)
    if (_01_) mem <= _05_;
  assign _02_ = ~ rwb;
  assign _01_ = & { _02_, rstn };
  assign _03_ = - (* src = "../src/spi_mem.sv:0.0-0.0" *) $signed({ 22'h000000, add, 4'h0 });
  assign _04_ = ~ (* src = "../src/spi_mem.sv:0.0-0.0" *) _06_;
  assign _05_ = _00_ | (* src = "../src/spi_mem.sv:0.0-0.0" *) _07_;
  assign _06_ = $signed(_03_) < 0 ? 16'hffff << - _03_ : 16'hffff >> _03_;
  assign _07_ = $signed(_03_) < 0 ? data_in << - _03_ : data_in >> _03_;
  wire [2047:0] _20_ = mem;
  assign _08_ = _20_[$signed({ 21'h000000, add, 4'h0 }) +: 16];
endmodule

(* top =  1  *)
(* src = "../src/spi_slave.sv:20.1-208.10" *)
module spi_slave(sdo, clk, reset_n, sclk, sdi, csz);
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  wire [3:0] _000_;
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  wire _001_;
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  wire _002_;
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  wire _003_;
  (* src = "../src/spi_slave.sv:172.4-206.7" *)
  wire [15:0] _004_;
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  wire [2:0] _005_;
  (* src = "../src/spi_slave.sv:172.4-206.7" *)
  wire [3:0] _006_;
  (* src = "../src/spi_slave.sv:177.17-177.28" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _007_;
  (* src = "../src/spi_slave.sv:188.19-188.33" *)
  wire [3:0] _008_;
  (* src = "../src/spi_slave.sv:139.11-139.52" *)
  wire _009_;
  (* src = "../src/spi_slave.sv:99.11-99.51" *)
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  (* src = "../src/spi_slave.sv:133.24-133.39" *)
  wire _028_;
  (* src = "../src/spi_slave.sv:139.12-139.27" *)
  wire _029_;
  (* src = "../src/spi_slave.sv:139.32-139.51" *)
  wire _030_;
  (* src = "../src/spi_slave.sv:148.20-148.34" *)
  wire _031_;
  (* src = "../src/spi_slave.sv:179.25-179.37" *)
  wire _032_;
  (* src = "../src/spi_slave.sv:99.12-99.23" *)
  wire _033_;
  (* src = "../src/spi_slave.sv:99.28-99.50" *)
  wire _034_;
  wire [2:0] _035_;
  wire [2:0] _036_;
  wire _037_;
  wire [2:0] _038_;
  wire _039_;
  wire [2:0] _040_;
  wire _041_;
  wire [3:0] _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire [3:0] _046_;
  wire _047_;
  wire [2:0] _048_;
  wire [2:0] _049_;
  (* src = "../src/spi_slave.sv:103.23-103.42" *)
  wire _050_;
  (* src = "../src/spi_slave.sv:133.23-133.54" *)
  wire _051_;
  (* src = "../src/spi_slave.sv:148.19-148.49" *)
  wire _052_;
  (* src = "../src/spi_slave.sv:179.24-179.52" *)
  wire _053_;
  (* src = "../src/spi_slave.sv:55.17-55.20" *)
  reg [6:0] add;
  (* src = "../src/spi_slave.sv:45.10-45.24" *)
  reg add_fetch_done;
  (* src = "../src/spi_slave.sv:26.10-26.13" *)
  input clk;
  wire clk;
  (* src = "../src/spi_slave.sv:41.16-41.23" *)
  reg [3:0] counter;
  (* src = "../src/spi_slave.sv:30.10-30.13" *)
  input csz;
  wire csz;
  (* src = "../src/spi_slave.sv:56.18-56.25" *)
  reg [15:0] data_in;
  (* src = "../src/spi_slave.sv:50.18-50.26" *)
  wire [15:0] data_out;
  (* src = "../src/spi_slave.sv:44.10-44.21" *)
  reg mem_op_done;
  (* src = "../src/spi_slave.sv:27.10-27.17" *)
  input reset_n;
  wire reset_n;
  (* src = "../src/spi_slave.sv:59.11-59.15" *)
  wire rstn;
  (* src = "../src/spi_slave.sv:57.11-57.14" *)
  reg rwb;
  (* src = "../src/spi_slave.sv:28.10-28.14" *)
  input sclk;
  wire sclk;
  (* src = "../src/spi_slave.sv:29.10-29.13" *)
  input sdi;
  wire sdi;
  (* src = "../src/spi_slave.sv:31.17-31.20" *)
  output sdo;
  reg sdo;
  (* src = "../src/spi_slave.sv:42.17-42.30" *)
  reg [15:0] serial_buffer;
  (* src = "../src/spi_slave.sv:43.16-43.21" *)
  reg [2:0] state;
  assign _007_ = counter + (* src = "../src/spi_slave.sv:177.17-177.28" *) 32'd1;
  assign _008_ = counter + (* src = "../src/spi_slave.sv:200.16-200.30" *) 1'h1;
  assign _009_ = _029_ & (* src = "../src/spi_slave.sv:155.11-155.52" *) _030_;
  assign _010_ = _033_ & (* src = "../src/spi_slave.sv:99.11-99.51" *) _034_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) add_fetch_done <= 1'h0;
    else if (_020_) add_fetch_done <= _050_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) add <= 7'h00;
    else if (_021_) add <= serial_buffer[6:0];
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) data_in <= 16'h0000;
    else if (_022_) data_in <= serial_buffer;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) state <= 3'h0;
    else if (_012_) state <= _005_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) sdo <= 1'h1;
    else if (_023_) sdo <= _003_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:172.4-206.7" *)
  always @(posedge sclk)
    if (_015_) counter <= _006_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:172.4-206.7" *)
  always @(posedge sclk)
    if (_016_) serial_buffer <= _004_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:172.4-206.7" *)
  always @(posedge sclk)
    if (_039_) add_fetch_done <= _053_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) rwb <= 1'h0;
    else if (_017_) rwb <= _002_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) mem_op_done <= 1'h0;
    else if (_018_) mem_op_done <= _001_;
  (* \always_ff  = 32'd1 *)
  (* src = "../src/spi_slave.sv:72.4-169.7" *)
  always @(posedge clk, negedge reset_n)
    if (!reset_n) counter <= 4'h0;
    else if (_024_) counter <= _000_;
  assign _011_ = | { _043_, _041_, _044_ };
  assign _012_ = | { _039_, _043_, _041_, _037_, _044_ };
  assign _013_ = { _044_, _009_ } != 2'h3;
  assign _014_ = | { _041_, _044_ };
  assign _015_ = | { _025_, _039_, _037_ };
  assign _016_ = | { _026_, _037_, _044_ };
  assign _017_ = | { _041_, _037_ };
  assign _018_ = | { _043_, _041_, _037_, _044_ };
  assign _019_ = { _025_, _009_ } != 2'h2;
  assign _027_ = ~ _010_;
  assign _020_ = & { _041_, _027_ };
  assign _021_ = & { _039_, add_fetch_done };
  assign _022_ = & { _043_, _009_ };
  assign _023_ = & { _013_, _014_ };
  assign _024_ = & { _019_, _011_ };
  assign _026_ = | { _043_, _039_ };
  assign _025_ = | { _044_, _043_ };
  assign _029_ = ! (* src = "../src/spi_slave.sv:155.12-155.27" *) counter;
  assign _030_ = ~ (* src = "../src/spi_slave.sv:155.32-155.51" *) mem_op_done;
  assign _031_ = counter == (* src = "../src/spi_slave.sv:163.20-163.34" *) 4'hf;
  assign _032_ = counter == (* src = "../src/spi_slave.sv:179.25-179.37" *) 4'h6;
  assign _028_ = counter == (* src = "../src/spi_slave.sv:185.9-185.21" *) 4'h7;
  assign _033_ = ~ (* src = "../src/spi_slave.sv:99.12-99.23" *) csz;
  assign _034_ = ~ (* src = "../src/spi_slave.sv:99.28-99.50" *) add_fetch_done;
  assign _035_ = rwb ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:125.7-125.18|../src/spi_slave.sv:125.4-129.7" *) 3'h5 : 3'h4;
  assign _036_ = mem_op_done ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:124.11-124.22|../src/spi_slave.sv:124.8-132.11" *) _035_ : 3'h3;
  assign _038_ = add_fetch_done ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:109.11-109.33|../src/spi_slave.sv:109.8-116.11" *) 3'h3 : 3'h2;
  assign _040_ = _010_ ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:99.11-99.51|../src/spi_slave.sv:99.8-104.11" *) 3'h2 : 3'h0;
  function [3:0] _097_;
    input [3:0] a;
    input [7:0] b;
    input [1:0] s;
    (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _097_ = b[3:0];
      2'b1?:
        _097_ = b[7:4];
      default:
        _097_ = a;
    endcase
  endfunction
  assign _000_ = _097_(4'hx, { 4'h0, _042_ }, { _041_, _025_ });
  assign _042_ = _009_ ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:139.11-139.52|../src/spi_slave.sv:139.8-149.11" *) 4'h0 : 4'hx;
  assign _045_ = _009_ ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:139.11-139.52|../src/spi_slave.sv:139.8-149.11" *) 1'hx : serial_buffer[15];
  function [0:0] _100_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _100_ = b[0:0];
      2'b1?:
        _100_ = b[1:1];
      default:
        _100_ = a;
    endcase
  endfunction
  assign _003_ = _100_(1'hx, { 1'h1, _045_ }, { _041_, _044_ });
  assign _044_ = state == (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *) 3'h5;
  function [0:0] _102_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _102_ = b[0:0];
      2'b1?:
        _102_ = b[1:1];
      default:
        _102_ = a;
    endcase
  endfunction
  assign _002_ = _102_(1'hx, { 1'h0, sdi }, { _041_, _037_ });
  assign _037_ = state == (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *) 3'h3;
  assign _041_ = ! (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *) state;
  assign _043_ = state == (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *) 3'h4;
  assign _039_ = state == (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *) 3'h2;
  function [15:0] _107_;
    input [15:0] a;
    input [47:0] b;
    input [2:0] s;
    (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:173.7-204.14" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _107_ = b[15:0];
      3'b?1?:
        _107_ = b[31:16];
      3'b1??:
        _107_ = b[47:32];
      default:
        _107_ = a;
    endcase
  endfunction
  assign _004_ = _107_(16'hxxxx, { data_out, serial_buffer[14:0], 1'h0, serial_buffer[14:0], sdi }, { _037_, _044_, _026_ });
  function [3:0] _108_;
    input [3:0] a;
    input [11:0] b;
    input [2:0] s;
    (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:173.7-204.14" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _108_ = b[3:0];
      3'b?1?:
        _108_ = b[7:4];
      3'b1??:
        _108_ = b[11:8];
      default:
        _108_ = a;
    endcase
  endfunction
  assign _006_ = _108_(4'hx, { _007_[3:0], _046_, _008_ }, { _039_, _037_, _025_ });
  assign _046_ = _028_ ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:185.9-185.21|../src/spi_slave.sv:185.5-189.8" *) 4'h0 : _008_;
  function [0:0] _110_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _110_ = b[0:0];
      3'b?1?:
        _110_ = b[1:1];
      3'b1??:
        _110_ = b[2:2];
      default:
        _110_ = a;
    endcase
  endfunction
  assign _001_ = _110_(1'hx, { 1'h0, _051_, _047_ }, { _041_, _037_, _025_ });
  assign _047_ = _009_ ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:139.11-139.52|../src/spi_slave.sv:139.8-149.11" *) 1'h1 : _052_;
  assign _048_ = _009_ ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:155.11-155.52|../src/spi_slave.sv:155.8-164.11" *) 3'h0 : 3'h4;
  function [2:0] _113_;
    input [2:0] a;
    input [14:0] b;
    input [4:0] s;
    (* src = "../src/spi_slave.sv:0.0-0.0|../src/spi_slave.sv:89.3-167.10" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _113_ = b[2:0];
      5'b???1?:
        _113_ = b[5:3];
      5'b??1??:
        _113_ = b[8:6];
      5'b?1???:
        _113_ = b[11:9];
      5'b1????:
        _113_ = b[14:12];
      default:
        _113_ = a;
    endcase
  endfunction
  assign _005_ = _113_(3'hx, { _040_, _038_, _036_, _049_, _048_ }, { _041_, _039_, _037_, _044_, _043_ });
  assign _049_ = _009_ ? (* full_case = 32'd1 *) (* src = "../src/spi_slave.sv:139.11-139.52|../src/spi_slave.sv:139.8-149.11" *) 3'h0 : 3'h5;
  assign _050_ = csz ? (* src = "../src/spi_slave.sv:103.23-103.42" *) 1'h0 : 1'h1;
  assign _051_ = _028_ ? (* src = "../src/spi_slave.sv:133.23-133.54" *) 1'h0 : 1'h1;
  assign _052_ = _031_ ? (* src = "../src/spi_slave.sv:163.19-163.49" *) 1'h0 : 1'h1;
  assign _053_ = _032_ ? (* src = "../src/spi_slave.sv:179.24-179.52" *) 1'h1 : 1'h0;
  (* module_not_derived = 32'd1 *)
  (* src = "../src/spi_slave.sv:61.12-69.18" *)
  spi_mem smem (
    .add(add),
    .clk(clk),
    .data_in(data_in),
    .data_out(data_out),
    .rstn(reset_n),
    .rwb(rwb)
  );
  assign rstn = reset_n;
endmodule
